- hosts: all
  become: yes
  tasks:
    - name: Install a package (example, this task triggers the reboot)
      ansible.builtin.apt:
        name: some-package
        state: present
      register: package_install
      notify:
        - Reboot the system

    - name: Wait for the system to be back online after reboot
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        timeout: 300
        delay: 10
      when: package_install.changed

  handlers:
    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 600  # Adjust based on how long the system takes to reboot
        test_command: uptime  # Command to check if the system is up
        pre_reboot_delay: 0  # Optional delay before reboot
        post_reboot_delay: 5  # Optional delay after reboot
      when: package_install.changed
